client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout,
  /bff/**
client-permit-all: >
  /login/**,
  /oauth2/**,
  /bff/**
post-logout-redirect-uri: ${gateway-uri}/ui/
resource-server-permit-all: >
  /,
  /login-options,
  /ui/**,
  /actuator/health/readiness,
  /actuator/health/liveness
server:
  port: 8481
  ssl:
    key-store: classpath:bff-server.p12
    key-store-password: changeme
    key-password: changeme

scheme: https
# issuer: http://keycloak.in.totterman.com:8080/realms/demo
issuer: https://keycloak.in.totterman.com:8443/realms/demo
client-id: spring-addons-confidential
client-secret: CdDSXNtXxdyNJP8Ho6WKEI9CbSHAuyUm
user-name-attribute: preferred_username
gateway-uri: ${scheme}://localhost:${server.port}

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
            user-name-attribute: ${user-name-attribute}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - offline_access
              - roles
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        # set a redirection from / to the UI
        - id: home
          uri: ${gateway-uri}
          predicates:
            - Path=/
          filters:
            - RedirectTo=301,${gateway-uri}/ui/
          #  - RedirectTo=301,${UI_URI:http://localhost:3000}
        # BFF access to greetings API (with TokenRelay replacing session cookies with access tokens)
        # To be used by SPAs (Angular app in our case)
        - id: greetings-api-bff
          uri: ${RESOURCE_URI:https://localhost:8482}
          predicates:
            - Path=/bff/v1/**
          filters:
            - TokenRelay=
            - StripPrefix=2
        - id: ui
          uri: ${UI_URI:http://localhost:3000}
          predicates:
            - Path=/ui/**
          metadata:
            cors:
              allowedOrigins: ${UI_URI:http://localhost:3000}
              allowedMethods:
                - GET
                - POST

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: INFO
        boot: INFO
        cloud:
          gateway:
            filter: TRACE

---
spring:
  config:
    activate:
      on-profile: ssl

scheme: https
server:
  ssl:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: mobile

pre-authorization-status: NO_CONTENT
post-authorization-status: NO_CONTENT

# gateway-uri: ${scheme}://10.0.2.2:${server.port}