client-security-matchers: >
  /login/**,
  /oauth2/**,
  /logout,
  /bff/**
client-permit-all: >
  /login/**,
  /oauth2/**,
  /bff/**
post-logout-redirect-uri: ${gateway-uri}/ui/
resource-server-permit-all: >
  /,
  /login-options,
  /ui/**,
  /actuator/health/readiness,
  /actuator/health/liveness,
  /favicon.ico

server:
  port: 8081
  ssl:
    enabled: false

scheme: http
issuer: http://localhost:8080/realms/demo
client-id: demo-client
client-secret: demo-keycloak-secret
user-name-attribute: preferred_username
gateway-uri: ${scheme}://localhost:${server.port}
greetings-api-uri: ${scheme}://localhost:8082
ui-uri: ${scheme}://localhost:3000

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
            user-name-attribute: ${user-name-attribute}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - offline_access
              - roles
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        # set a redirection from / to the UI
        - id: home
          uri: ${gateway-uri}
          predicates:
            - Path=/
          filters:
            - RedirectTo=301,${gateway-uri}/ui/
        # BFF access to greetings API (with TokenRelay replacing session cookies with access tokens)
        # To be used by SPAs (Angular app in our case)
        - id: greetings-api-bff
          uri: ${greetings-api-uri}
          predicates:
            - Path=/bff/v1/**
          filters:
            - TokenRelay=
            - StripPrefix=2
        - id: ui
          uri: ${ui-uri}
          predicates:
            - Path=/ui/**,/api/live/ws

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO
        cloud:
          gateway: DEBUG

---
spring:
  config:
    activate:
      on-profile: ssl

scheme: https
server:
  ssl:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: mobile

pre-authorization-status: NO_CONTENT
post-authorization-status: NO_CONTENT

# gateway-uri: ${scheme}://10.0.2.2:${server.port}
