issuer: https://keycloak.in.totterman.com:8443/realms/demo
#issuer: http://localhost:8080/realms/demo

server:
  # port: 8082
  port: 8482
  ssl:
    key-store: classpath:greeting-server.p12
    key-store-password: changeme
    key-password: changeme

permit-all: >
  /users/me,
  /actuator/health/readiness,
  /actuator/health/liveness

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
          oauth2: TRACE
        web: DEBUG

---
server:
  ssl:
    enabled: false

spring:
  config:
    activate:
      on-profile: ssl