version: '3.9'
services:

  demo-keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: "demo-keycloak"
    command: start-dev --import-realm --log-level="DEBUG"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      demonet:

networks:
  demonet:
    driver: bridge
