apiVersion: v1
kind: Service
metadata:
  name: greeting-server
  labels:
    app: greeting-server
spec:
  type: ClusterIP
  selector:
    app: greeting-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8482